const UPDATE_QUERY = 'UPDATE_QUERY';
const SUBMIT_QUERY = 'SUBMIT_QUERY';
const REVOKE_SUBMIT_QUERY = 'REVOKE_SUBMIT_QUERY';
const CLEAR_QUERY = 'CLEAR_QUERY';

export {
  UPDATE_QUERY,
  SUBMIT_QUERY,
  REVOKE_SUBMIT_QUERY,
  CLEAR_QUERY
};
